### ISSUE TITLE
`TypeError: 'NoneType' object is not subscriptable` (`self.hist = self.cli.history(self.img['RepoTags'][0])`)

### ISSUE THREAD

**Issue by stdedos** [mrhavens/Dedockify#3]
```py
Traceback (most recent call last):
  File "/app/dedockify.py", line 55, in <module>
    __main__ = MainObj()
  File "/app/dedockify.py", line 16, in __init__
    self.hist = self.cli.history(self.img['RepoTags'][0])
TypeError: 'NoneType' object is not subscriptable
```

I think the problem is that I pulled an image as a `sha256:xxx` instead of a tagged one

**Comment by johndpope** [comment]
same.

**Comment by johndpope** [comment]
you can use

       self.hist = self.cli.history(self.img['RepoDigests'][0])


![Screenshot from 2022-11-29 22-36-02](https://user-images.githubusercontent.com/289994/205835239-14662207-2a0f-40ea-ab97-322da50c73a1.png)

**Comment by johndpope** [comment]
![Screenshot from 2022-12-06 17-11-24](https://user-images.githubusercontent.com/289994/205835380-01bf25a3-45bc-439d-a423-f9eb5e4e334b.png)

you can easily debug with python - just set the args with image id.
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "args" : ["2d398b66fa04"]
        }
    ]
}
```
